### ISSUE TITLE
Arrays of functions are not meaningful when building sample-sources/watchpoint_clients.c

### ISSUE THREAD

**Issue by NoyaFangzhou** [ParCoreLab/ReuseTracker#2]
I try to build this tool but I met this issue.
```sample-sources/watchpoint_clients.c: In function ‘PopulateBlackListAddresses’:
sample-sources/watchpoint_clients.c:901:13: error: arrays of functions are not meaningful
  901 | static void PopulateBlackListAddresses() {
```
I use ```gcc``` version 12.1.1 and with flag ```std=c++11```

**Comment by msasongko17** [comment]
I will try to fix this bug. Meanwhile, you can try to build this tool using gcc version 9.x.x. This is the last gcc version that works on ReuseTracker.

**Comment by msasongko17** [comment]
I solved the problem. It was caused by the static analyzer in gcc 12. I solved it by changing the line
blackListAddresses[numBlackListAddresses].startAddr = ((void *)__tls_get_addr) - 1000; into
blackListAddresses[numBlackListAddresses].startAddr = (void *) (((uint64_t) __tls_get_addr) - 1000);
in function PopulateBlackListAddresses.
