### ISSUE TITLE
Tutorials and documentation

### ISSUE THREAD

**Issue by dendibakh** [ParCoreLab/ReuseTracker#3]
Hello, ReuseTracker seems to be a promising tool to quantify the spatial and temporal locality of a program. Hats off to your work, very good research!
Is there any tutorial that will help me to learn how to interpret the output data?
I have a small naive matrix multiply program, which I know has a bad locality. I do the straightforward loop interchange transformation to fix the locality problem (and maybe loop tiling/blocking to improve it further). I want to see the effect of my transformation. And develop the intuition of where should I look to find problems in the future.
I followed the steps in the README, but still having a hard time interpreting the output data. I have never used hpctoolkit before. Is there a "hello-world" example, which will explain where to look for and how to make sense of the collected data?
BTW, tried using `loca` and `RDX` previously, but there is a lack of documentation as well.

**Comment by msasongko17** [comment]
Hi Denis, I know that I have replied you by email, but I will still address your points here so that this info can be useful for others. 

"Is there any tutorial that will help me to learn how to interpret the output data?"

In a reuse distance histogram, the x axis shows the reuse distance while the y axis shows the percent of reuses whose distances are the reuse distances pointed by the x axis. The output file of reusetracker that ends with *-PID.reuse.hpcrun in the *_output folder captures the time reuse distance histogram, the numbers in the first column show the ranges of reuses while the numbers in the second column show the counts of reuses whose time reuse distances are within the ranges specified by the numbers in the first column. By default, the ranges of reuses in the first column are reported with log base 2-scaling. For example, if the first number in the first column is 4000, the second number will be 8000, the third is 16000, etc, and the first range of reuses covered in the first bin is within the range of 0-4000, the second range covered in the second bin is within the range of 4001-8000, etc.      

Note that this raw output is in the form of a time reuse distance histogram. To convert it into stack reuse distance histogram, you have to use the python script in https://github.com/ParCoreLab/ReuseTracker/blob/master/time-to-stack-conversion/reuse_distance_histo.py .

"I have a small naive matrix multiply program, which I know has a bad locality. I do the straightforward loop interchange transformation to fix the locality problem (and maybe loop tiling/blocking to improve it further). I want to see the effect of my transformation. And develop the intuition of where should I look to find problems in the future."

Yes, you can profile your code using RDX and ReuseTracker before and after your transformation to see the change in reuse distance pattern. If we disregard inter-thread cache line invalidations, poor data locality in L2 caches can be predicted if there are long reuse distances whose lengths are longer than the size of L2 cache in the stack reuse distance histogram.

"I followed the steps in the README, but still having a hard time interpreting the output data. I have never used hpctoolkit before. Is there a "hello-world" example, which will explain where to look for and how to make sense of the collected data?"

In order to be 100% sure of the correctness of the reuse distances measured by ReuseTracker, I suggest you write the test code in assembly language. You can insert several lines of assembly code to C code using GCC inline assembly: https://www.ibiblio.org/gferg/ldp/GCC-Inline-Assembly-HOWTO.html. The reason for testing using assembly language instead of a higher level language is to prevent code transformations by compilers. If the code is in a high level language, variable reads and assignments might be transformed into register reads and writes instead of memory operations, and therefore, we cannot be sure of the reuse distance that we expect from the code.

An example of a test code is the one here: https://github.com/ParCoreLab/ReuseTracker/blob/master/reuse-invalidation-benchs/reuse-invalidation.c . Using this code, you can control the reuse distances and the number of reuses that are to be generated by the code. The parameters that you need to configure to shape the reuse distance pattern are described in my paper https://dl.acm.org/doi/10.1145/3484199 . There are also examples on how to run it in this Makefile: https://github.com/ParCoreLab/ReuseTracker/blob/master/Makefile .  

"BTW, tried using loca and RDX previously, but there is a lack of documentation as well."

Loca can be installed by following the instructions in https://github.com/dcompiler/loca/blob/master/doc/index.html.

The RDX in the original repo is no longer maintained. However, I actually still maintain both RDX and ReuseTracker in this repository. To install RDX, you have to take the same steps needed to install ReuseTracker, and to run it, you have to run one of the commands in https://github.com/ParCoreLab/hpctoolkit/blob/master/ReuseTracker.HowToRun by replacing WP_REUSETRACKER with WP_REUSE.
